version: '3'
services:
  product-service:
    build: ./backend/product-service
    ports:
      - "5000:5000"
  user-service:
    build: ./backend/user-service
    ports:
      - "5001:5001"
  order-service:
    build: ./backend/order-service
    ports:
      - "5002:5002"
  frontend:
    build: ./frontend/react-app
    ports:
      - "3000:3000"
